name: video_box
description: A control that plays video in flutter, I make the control as flexible as possible, can play a single video, video list on the page.
version: 0.17.0
homepage: https://github.com/januwA/flutter_video_box

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.7
  mobx: ^2.1.0
  flutter_mobx: ^2.0.6
  connectivity_plus: ^2.3.7 # 监听网络连接
  sensors_plus: ^1.3.4 # 监听设备旋转
  dart_printf: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:

flutter: