name: video_box
description: A control that plays video in flutter, I make the control as flexible as possible, can play a single video, video list on the page.
version: 0.11.0
homepage: https://github.com/januwA/flutter_video_box

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.5
  mobx: ^1.0.2
  flutter_mobx: ^1.0.1
  sensors: ^0.4.1+7
  connectivity: ^0.4.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:

flutter: